### PR TITLE
don't install extra jars by default

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by briandealwis** [comment]
Wouldn't it be easier to not install the App Engine facet by default when adding the runtime?

**Comment by elharo** [comment]
Presumably we need the facet to ID projects as app engine projects, even if it's not adding jars to the classpath. The change here is that we do not automatically add these jars to all app engine apps.

**Comment by briandealwis** [comment]
I had been thinking that we could check if the project specified an _App Engine Standard_ runtime. But I'll retract that: having a facet means we could have a project targeted to the generic HTTP runtime.

**Comment by briandealwis** [comment]
So shouldn't we remove this classpath initializer and the corresponding `org.eclipse.jdt.core.classpathContainerInitializer` extension in `plugin.xml` too?

Seems we should also add support for a facet detector (`org.eclipse.wst.common.project.facet.core.detectors`) to automagically detect and add the facet on import.

**Comment by akerekes** [comment]
If we don't install anything, why don't we just get rid of the whole class?

**Comment by briandealwis** [comment]
Or better yet, move it to a new facet.

**Comment by elharo** [comment]
PTAL. I was trying for the minimal necessary change, but now I've removed the installation of the jars when the facet is installed.

**Comment by akerekes** [comment]
LGTM (assuming Travis passes)

**Pull request merged**
