### PR TITLE
Create an IDebugTarget for the Dev App Server

### LINKED ISSUE #614: _Run_ launches must register a debug target or process with the ILaunch
If we use _Run_ to start the server, a launch configuration appears in the _Debug_ view that cannot be terminated as there are no associated processes or debug target resources.
will not disappear

Basically `LocalAppEngineServerLaunchConfigurationDelegate#launch()` needs to associate an `IProcess` (perhaps the CloudSdk's process?) or an `IDebugTarget` with 
the `Launch` instance.  The normal JavaLaunchDelegate (_Run As Java Application_) uses `DebugPlugin.newProcess()` to add a wrapper around a `java.lang.Process`.

Thence the launch can be terminated and removed.

### PR DESCRIPTION
**Pull request by briandealwis**
Required for _Run_ launches to be able to be terminated.  Not required for _Debug_ launches as the the remote JVMs are added to the launch as they attach to the debugger.

Fixes #614 

Hard to test: will enhance the ITs test to test the various combinations separately.

### CODE REVIEW

**Comment by chanseokoh** [comment]
I absolutely have no idea, but it sounds like you said in #614 we might be able to use `DebugPlugin.newProcess()` if we can get a `java.lang.Process` of `CloudSdk`? (I believe getting a process is trivial with `addStartListener`, which is being done for deployment.) By that way, I wonder if we can avoid implementing `IDebugTarget` ourselves, if that's simpler. But I really have no idea about what's going on here; just throwing out a random thought.

**Comment by briandealwis** [comment]
I didn't explore the `IProcess` approach.  My intuition was that the _Stop/Terminate_ button would actually call `Process#destroy()` on that instance, and we wouldn't necessarily get any proper server cleanup.  The `IDebugTarget` seemed conceptually simple.

The other implementations of `IDebugTarget` inherit from a `DebugElement` abstract class, but it seemed more of a hindrance than a help :-/

**Comment by briandealwis** [comment]
> My intuition was that the Stop/Terminate button would actually call Process#destroy() on that instance

And [confirmed](https://github.com/eclipse/eclipse.platform.debug/blob/master/org.eclipse.debug.core/core/org/eclipse/debug/core/model/RuntimeProcess.java#L204).

**Comment by chanseokoh** [comment]
Well thought out!

**Comment by briandealwis** [comment]
>  a DebugElement abstract class, but it seemed more of a hindrance than a help :-/

But inheriting from `DebugElement` does bring some other advantages, like the adapter support.  I'll revisit this.

**Comment by elharo** [comment]
LGTM assuming tests pass

**Pull request merged**
